version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.0-apache
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t mfieldhouse/docker-php-helloworld:$CIRCLE_BRANCH .


